<a href="https://colab.research.google.com/github/redsoil/myPython/blob/main/ds_project1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import files

In [2]:
uploaded = files.upload()

Saving df.csv to df.csv

In [3]:
import pandas as pd

In [4]:
df = pd.read_csv('df.csv')

In [5]:
df

,Job Title,Salary Estimate,Rating,Company Name,Location,Size,Founded,Type of ownership,Industry,Sector,Revenue
0,Senior Data Scientist,$111K-$181K (Glassdoor est.),3.5,Hopper\n3.5,"New York, NY",501 to 1000 employees,2007,Company - Private,Travel Agencies,Travel & Tourism,Unknown / Non-Applicable
1,"Data Scientist, Product Analytics",$111K-$181K (Glassdoor est.),4.5,Noom US\n4.5,"New York, NY",1001 to 5000 employees,2008,Company - Private,"Health, Beauty, & Fitness",Consumer Services,Unknown / Non-Applicable
2,Data Science Manager,$111K-$181K (Glassdoor est.),-1.0,Decode_M,"New York, NY",1 to 50 employees,-1,Unknown,-1,-1,Unknown / Non-Applicable
3,Data Analyst,$111K-$181K (Glassdoor est.),3.4,Sapphire Digital\n3.4,"Lyndhurst, NJ",201 to 500 employees,2019,Company - Private,Internet,Information Technology,Unknown / Non-Applicable
4,"Director, Data Science",$111K-$181K (Glassdoor est.),3.4,United Entertainment Group\n3.4,"New York, NY",51 to 200 employees,2007,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable
...,...,...,...,...,...,...,...,...,...,...,...
5887,Manufacturing Data Analyst Engineer,$42K - $76K (Glassdoor est.),3.6,Hose Master\n3.6,"Euclid, OH",201 to 500 Employees,1982,Company - Private,Electrical & Electronic Manufacturing,Manufacturing,Unknown / Non-Applicable
5888,Data Scientist,-1,4.9,Bluetree Network\n4.9,"Madison, WI",-1,-1,-1,-1,-1,-1
5889,Supply Chain Consultant - Data Scientist,-1,4.0,"Kimberly-Clark Corporation, LLC\n4.0","Neenah, WI",10000+ Employees,1872,Company - Public,Consumer Products Manufacturing,Manufacturing,$10+ billion (USD)
5890,Data Science Engineer,-1,4.0,AE Business Solutions\n4.0,"Madison, WI",51 to 200 Employees,1949,Company - Private,Computer Hardware & Software,Information Technology,$25 to $50 million (USD)
5891,Data Scientist/ Full Stack Developer,$65 - $72 Per Hour,3.7,Epitec\n3.7,"Wisconsin, WI",1001 to 5000 Employees,1978,Company - Private,Staffing & Outsourcing,Business Services,$100 to $500 million (USD)

In [6]:
df.head()

,Job Title,Salary Estimate,Rating,Company Name,Location,Size,Founded,Type of ownership,Industry,Sector,Revenue
0,Senior Data Scientist,$111K-$181K (Glassdoor est.),3.5,Hopper\n3.5,"New York, NY",501 to 1000 employees,2007,Company - Private,Travel Agencies,Travel & Tourism,Unknown / Non-Applicable
1,"Data Scientist, Product Analytics",$111K-$181K (Glassdoor est.),4.5,Noom US\n4.5,"New York, NY",1001 to 5000 employees,2008,Company - Private,"Health, Beauty, & Fitness",Consumer Services,Unknown / Non-Applicable
2,Data Science Manager,$111K-$181K (Glassdoor est.),-1.0,Decode_M,"New York, NY",1 to 50 employees,-1,Unknown,-1,-1,Unknown / Non-Applicable
3,Data Analyst,$111K-$181K (Glassdoor est.),3.4,Sapphire Digital\n3.4,"Lyndhurst, NJ",201 to 500 employees,2019,Company - Private,Internet,Information Technology,Unknown / Non-Applicable
4,"Director, Data Science",$111K-$181K (Glassdoor est.),3.4,United Entertainment Group\n3.4,"New York, NY",51 to 200 employees,2007,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable

In [7]:
df.tail()

,Job Title,Salary Estimate,Rating,Company Name,Location,Size,Founded,Type of ownership,Industry,Sector,Revenue
5887,Manufacturing Data Analyst Engineer,$42K - $76K (Glassdoor est.),3.6,Hose Master\n3.6,"Euclid, OH",201 to 500 Employees,1982,Company - Private,Electrical & Electronic Manufacturing,Manufacturing,Unknown / Non-Applicable
5888,Data Scientist,-1,4.9,Bluetree Network\n4.9,"Madison, WI",-1,-1,-1,-1,-1,-1
5889,Supply Chain Consultant - Data Scientist,-1,4.0,"Kimberly-Clark Corporation, LLC\n4.0","Neenah, WI",10000+ Employees,1872,Company - Public,Consumer Products Manufacturing,Manufacturing,$10+ billion (USD)
5890,Data Science Engineer,-1,4.0,AE Business Solutions\n4.0,"Madison, WI",51 to 200 Employees,1949,Company - Private,Computer Hardware & Software,Information Technology,$25 to $50 million (USD)
5891,Data Scientist/ Full Stack Developer,$65 - $72 Per Hour,3.7,Epitec\n3.7,"Wisconsin, WI",1001 to 5000 Employees,1978,Company - Private,Staffing & Outsourcing,Business Services,$100 to $500 million (USD)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5892 entries, 0 to 5891
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Job Title          5892 non-null   object
 1   Salary Estimate    5892 non-null   object
 2   Rating             5892 non-null   float64
 3   Company Name       5892 non-null   object
 4   Location           5892 non-null   object
 5   Size               5892 non-null   object
 6   Founded            5892 non-null   object
 7   Type of ownership  5892 non-null   object
 8   Industry           5892 non-null   object
 9   Sector             5892 non-null   object
 10  Revenue            5892 non-null   object
dtypes: float64(1), object(10)
memory usage: 506.5+ KB

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5892 entries, 0 to 5891
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Job Title          5892 non-null   object
 1   Salary Estimate    5892 non-null   object
 2   Rating             5892 non-null   float64
 3   Company Name       5892 non-null   object
 4   Location           5892 non-null   object
 5   Size               5892 non-null   object
 6   Founded            5892 non-null   object
 7   Type of ownership  5892 non-null   object
 8   Industry           5892 non-null   object
 9   Sector             5892 non-null   object
 10  Revenue            5892 non-null   object
dtypes: float64(1), object(10)
memory usage: 506.5+ KB

In [10]:
df['Job Title'].value_counts()

Job Title
Data Scientist                              703
Data Analyst                                362
Data Engineer                               317
Senior Data Scientist                       141
Machine Learning Engineer                    72
                                           ...
Scientist Medical Laboratory II               1
IT Data Science Analyst                       1
Research Scientist Associate IV               1
Laboratory Scientist II                       1
Supply Chain Consultant - Data Scientist      1
Name: count, Length: 2959, dtype: int64

In [11]:
df['Location'].value_counts()

Location
Austin, TX         345
Chicago, IL        333
San Diego, CA      331
New York, NY       303
Los Angeles, CA    234
                  ...
Redlands, CA         1
Pittsburg, CA        1
Elk Grove, CA        1
Coronado, CA         1
Wisconsin, WI        1
Name: count, Length: 545, dtype: int64

In [12]:
myList1 = [1, 2, 3, 4, 5, 6, 7, 8 , 9, 2, 5 ,1, 5 ,0]

In [13]:
myList1

[1, 2, 3, 4, 5, 6, 7, 8, 9, 2, 5, 1, 5, 0]

In [14]:
myList1.count(2)

2

In [15]:
myList1.count(5)

3

In [16]:
d = {'first name' : 'Ali', 'last name' : 'Raeisi', 'id' : '13824576310', 'degree' : 'It'}
d['first name']

'Ali'

In [17]:
d['id']

'13824576310'

In [18]:
my_dict = d

In [19]:
my_dict

{'first name': 'Ali',
 'last name': 'Raeisi',
 'id': '13824576310',
 'degree': 'It'}

In [20]:
my_dict['degree']

'It'

In [21]:
5 == 5

True

In [22]:
7 != 8

True

In [25]:
max(myList1)

9

In [24]:
myList1

[1, 2, 3, 4, 5, 6, 7, 8, 9, 2, 5, 1, 5, 0]